matrix:
- name: Markdown
  aspell:
    lang: en
  dictionary:
    wordlists:
      - .wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.html:
  - pyspelling.filters.markdown:
    ignores:
      - code
      - pre
  sources:
  - '**/*.md'
  default_encoding: utf-8
