name: Pandoc Action
on: [push,pull_request,workflow_dispatch]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Pandoc Document Converter pdf
        uses: Ender-events/pandoc@master
        with:
          args: '--pdf-engine=xelatex  --template=templates/eisvogel.latex  --highlight-style zenburn --toc -N --lua-filter _pandoc_filter/image_link.lua  --lua-filter _pandoc_filter/add_title.lua  -o assets/btcguide.pdf  index.md'
      - name: Pandoc Document Converter -epub
        uses: Ender-events/pandoc@master
        with:
          args: '--css .\templates\epub.css --toc -N --toc-depth=1 --lua-filter _pandoc_filter/image_link.lua  --lua-filter _pandoc_filter/add_title.lua  -o assets/btcguide.epub  index.md'
